### PR TITLE
added support for browser verison and the browser-dgram messagechannel…

### PR DESCRIPTION
**Pull request by ondras**
… implementation

See https://github.com/hundredrabbits/Pilot/pull/37 for reference.

### CODE REVIEW

**Review by jakofranko — CHANGES_REQUESTED** [review]
Could you move the index.html file into the `browser` directory? That way we have all the browser things in there and can keep the root directory relatively empty.

Also, I tried to run this in my browser with a little node http server and couldn't get it to play any notes. Do you have any suggestions for getting it running the way you run it on your machine?

**Comment by ondras** [comment]
I will have a look. I have not seen this code nor Pilot nor Orca for three years :-)

**Comment by jakofranko** [comment]
It's been a while since I've looked at the code too haha, I just started getting back into this stuff myself. Let me know if you run into any issues, I'd be happy to help out.

**Comment by ondras** [comment]
Hmm, the console is filled/killed with thousands of warning messages from tone.js. And few real JS errors as well.

**Comment by ondras** [comment]
I moved the `index.html` to `browser/` and pegged the Tone.js dependency to major version 13 (latest is 14 and is probably Pilot-incompatible). I managed to make some sounds this way :-)

**Comment by jakofranko** [comment]
Excellent! I'll take a look sometime today. I'll have to look into the tone.js stuff. Yesterday I updated the version of electron which should have taken care of all those vulnerability alerts. Tone.js can be next.

**Comment by jakofranko** [comment]
Are you sure you pushed up your changes? Looks like you removed `index.html` but I don't see it in `browser/` 🤔

**Comment by ondras** [comment]
Yeah, sorry for that. Included & pushed right now.

**Comment by jakofranko** [comment]
Great, I see it now! How are you serving this on your local machine? Serving `index.html` directly doesn't load the JS, so I'm guessing you have something bootstrapped to load it; that might be useful to include in this PR too so that it could be developed easily. Or if you want the user to use their own web server, maybe add a `README` to the `browser` directory with some instructions/recommendations on serving `index.html`. Loading it directly in the browser throws CORS errors (expected).

**Comment by ondras** [comment]
> Great, I see it now! How are you serving this on your local machine?

Using any web server that is currently available. Typically via Apache or `php -S`.



> . Loading it directly in the browser throws CORS errors (expected

Yeah, because ES modules need to be CORS-enabled.

> Or if you want the user to use their own web server, maybe add a `README` to the `browser` directory with some instructions/recommendations on serving `index.html`.

Hmm, I would say that having your infrastructure set up is somewhat out of the scope for the project itself. But I can add that, if you wish.

**Comment by jakofranko** [comment]
>  I would say that having your infrastructure set up is somewhat out of the scope for the project itself.

Fair enough and I'm good with saying "here's a browser version but you have to figure out how to host it yourself."

**Review by jakofranko — APPROVED** [review]

**Pull request merged**
